services:
  - type: web
    name: hardware-sets-ark-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://support_db_user:Ark%402811@hardware-selection.dcnpff4.mongodb.net/hardware_selection?retryWrites=true&w=majority&appName=hardware-selection
      - key: JWT_SECRET
        value: hardwareSelectionSecretKey2024ProjectFinal
      - key: PORT
        value: 10000